version: '3'

services:

  nginx:
    image: nginx:1.13.8-alpine
    depends_on:
      - api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${LOG_PATH:-/var/log}:/var/log
    ports:
      - "5011:80"

  api:
    ports:
      - "5008:80"